name: Generate Snake Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: srinathesampally
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push snake animation to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
